name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install the dependencies
        run: yarn install
      - name: Run the tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test --coverage

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install the dependencies
        run: yarn install
      - name: Build the application
        run: yarn release -w
      - name: Release the application
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/ElectronReactVite-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
